In [7]:
import pandas as pd
import os

In [8]:
silver_path = r"C:\Users\yashk\OneDrive\Desktop\Logistics_Data_Pipeline\Silver"

In [9]:
gold_dataframes = {}
for folder in os.listdir(silver_path):
    folder_path = os.path.join(silver_path, folder)
    if os.path.isdir(folder_path):
        file = os.listdir(folder_path)[0]
        file_path = os.path.join(folder_path, file)
        df = pd.read_csv(file_path)
        gold_dataframes[folder] = df
print(gold_dataframes.keys())

dict_keys(['customers', 'delivery_events', 'drivers', 'driver_monthly_metrics', 'facilities', 'fuel_purchases', 'loads', 'maintenance_records', 'routes', 'safety_incidents', 'trailers', 'trips', 'trucks', 'truck_utilization _metrics'])

In [10]:
drivers = gold_dataframes["drivers"]
driver_metrics = gold_dataframes["driver_monthly_metrics"]
drivers.head()

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,NaN,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19
3,DRV00004,Barbara,Brown,2013-09-08,NaN,DL735540030,WA,1995-02-06,Denver,Active,A,19
4,DRV00005,Mary,Martinez,2018-12-02,NaN,DL706011277,AZ,1960-07-15,Chicago,Active,A,12

In [11]:
print(drivers.columns.tolist())
print(driver_metrics.columns.tolist())

['driver_id', 'first_name', 'last_name', 'hire_date', 'termination_date', 'license_number', 'license_state', 'date_of_birth', 'home_terminal', 'employment_status', 'cdl_class', 'years_experience']
['driver_id', 'month', 'trips_completed', 'total_miles', 'total_revenue', 'average_mpg', 'total_fuel_gallons', 'on_time_delivery_rate', 'average_idle_hours']

In [12]:
drivers.head()

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,NaN,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19
3,DRV00004,Barbara,Brown,2013-09-08,NaN,DL735540030,WA,1995-02-06,Denver,Active,A,19
4,DRV00005,Mary,Martinez,2018-12-02,NaN,DL706011277,AZ,1960-07-15,Chicago,Active,A,12

In [13]:
driver_metrics.head()

,driver_id,month,trips_completed,total_miles,total_revenue,average_mpg,total_fuel_gallons,on_time_delivery_rate,average_idle_hours
0,DRV00001,2022-01-01,26,36620,79141.59,6.61,5574.7,0.385,8.2
1,DRV00001,2022-02-01,9,13515,27133.87,6.69,2095.1,0.333,6.8
2,DRV00001,2022-03-01,20,30361,62399.62,6.36,4792.2,0.550,7.5
3,DRV00001,2022-04-01,19,28127,68161.13,6.61,4251.4,0.474,8.4
4,DRV00001,2022-05-01,14,16071,36256.82,6.35,2573.1,0.214,6.8

In [14]:
print(drivers.columns.tolist())

['driver_id', 'first_name', 'last_name', 'hire_date', 'termination_date', 'license_number', 'license_state', 'date_of_birth', 'home_terminal', 'employment_status', 'cdl_class', 'years_experience']

In [15]:
print(driver_metrics.columns.tolist())

['driver_id', 'month', 'trips_completed', 'total_miles', 'total_revenue', 'average_mpg', 'total_fuel_gallons', 'on_time_delivery_rate', 'average_idle_hours']

In [16]:
driver_performance = pd.merge(
    drivers,
    driver_metrics,
    on="driver_id",
    how="left"
)
driver_performance.head()

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience,month,trips_completed,total_miles,total_revenue,average_mpg,total_fuel_gallons,on_time_delivery_rate,average_idle_hours
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3,2022-01-01,26.0,36620.0,79141.59,6.61,5574.7,0.385,8.2
1,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3,2022-02-01,9.0,13515.0,27133.87,6.69,2095.1,0.333,6.8
2,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3,2022-03-01,20.0,30361.0,62399.62,6.36,4792.2,0.550,7.5
3,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3,2022-04-01,19.0,28127.0,68161.13,6.61,4251.4,0.474,8.4
4,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3,2022-05-01,14.0,16071.0,36256.82,6.35,2573.1,0.214,6.8

In [17]:
driver_performance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4490 entries, 0 to 4489
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   driver_id              4490 non-null   object
 1   first_name             4490 non-null   object
 2   last_name              4490 non-null   object
 3   hire_date              4490 non-null   object
 4   termination_date       26 non-null     object
 5   license_number         4490 non-null   object
 6   license_state          4490 non-null   object
 7   date_of_birth          4490 non-null   object
 8   home_terminal          4490 non-null   object
 9   employment_status      4490 non-null   object
 10  cdl_class              4490 non-null   object
 11  years_experience       4490 non-null   int64
 12  month                  4464 non-null   object
 13  trips_completed        4464 non-null   float64
 14  total_miles            4464 non-null   float64
 15  total_revenue          4464 non-null   float64
 16  average_mpg            4464 non-null   float64
 17  total_fuel_gallons     4464 non-null   float64
 18  on_time_delivery_rate  4464 non-null   float64
 19  average_idle_hours     4464 non-null   float64
dtypes: float64(7), int64(1), object(12)
memory usage: 701.7+ KB

In [18]:
driver_summary = driver_performance.groupby(
    ["driver_id", "first_name", "last_name"]
).agg({
    "trips_completed": "sum",
    "total_miles": "sum",
    "total_revenue": "sum",
    "total_fuel_gallons": "sum",
    "average_mpg": "mean",
    "on_time_delivery_rate": "mean",
    "average_idle_hours": "mean"
}).reset_index()

driver_summary.head()

,driver_id,first_name,last_name,trips_completed,total_miles,total_revenue,total_fuel_gallons,average_mpg,on_time_delivery_rate,average_idle_hours
0,DRV00001,Jennifer,Hernandez,632.0,930236.0,1985683.26,144705.9,6.484722,0.454167,7.036111
1,DRV00002,William,Martin,662.0,943246.0,2073621.50,146600.7,6.505000,0.468389,7.108333
2,DRV00003,Charles,Hernandez,677.0,1010235.0,2146977.47,155897.8,6.539444,0.450806,6.797222
3,DRV00004,Barbara,Brown,659.0,982625.0,2119361.45,152143.0,6.517222,0.428333,7.002778
4,DRV00005,Mary,Martinez,643.0,923128.0,2022357.46,143472.8,6.512222,0.454056,7.136111

In [31]:
driver_summary = driver_performance.groupby(
    ["driver_id", "first_name", "last_name"]
).agg({
    "trips_completed": "sum",
    "total_miles": "sum",
    "total_revenue": "sum",
    "total_fuel_gallons": "sum",
    "average_mpg": "mean",
    "on_time_delivery_rate": "mean",
    "average_idle_hours": "mean"
}).reset_index()
driver_summary.head()

,driver_id,first_name,last_name,trips_completed,total_miles,total_revenue,total_fuel_gallons,average_mpg,on_time_delivery_rate,average_idle_hours
0,DRV00001,Jennifer,Hernandez,632.0,930236.0,1985683.26,144705.9,6.484722,0.454167,7.036111
1,DRV00002,William,Martin,662.0,943246.0,2073621.50,146600.7,6.505000,0.468389,7.108333
2,DRV00003,Charles,Hernandez,677.0,1010235.0,2146977.47,155897.8,6.539444,0.450806,6.797222
3,DRV00004,Barbara,Brown,659.0,982625.0,2119361.45,152143.0,6.517222,0.428333,7.002778
4,DRV00005,Mary,Martinez,643.0,923128.0,2022357.46,143472.8,6.512222,0.454056,7.136111

In [33]:
driver_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   driver_id              150 non-null    object
 1   first_name             150 non-null    object
 2   last_name              150 non-null    object
 3   trips_completed        150 non-null    float64
 4   total_miles            150 non-null    float64
 5   total_revenue          150 non-null    float64
 6   total_fuel_gallons     150 non-null    float64
 7   average_mpg            124 non-null    float64
 8   on_time_delivery_rate  124 non-null    float64
 9   average_idle_hours     124 non-null    float64
dtypes: float64(7), object(3)
memory usage: 11.8+ KB

In [37]:
gold_path = r"C:\Users\yashk\OneDrive\Desktop\Logistics_Data_Pipeline\Gold"

In [39]:
import os

driver_summary_folder = os.path.join(gold_path, "driver_performance_summary")
os.makedirs(driver_summary_folder, exist_ok=True)

driver_summary.to_csv(
    os.path.join(driver_summary_folder, "driver_performance_summary.csv"),
    index=False
)

print("✅ Driver Performance Summary saved successfully!")

✅ Driver Performance Summary saved successfully!

In [41]:
import pandas as pd

customers = pd.read_csv("../Silver/customers/customers.csv")
customers.head()

,customer_id,customer_name,customer_type,credit_terms_days,primary_freight_type,account_status,contract_start_date,annual_revenue_potential
0,CUST00001,Metro Wholesale,Dedicated,60,General,Inactive,2020-02-20,985117
1,CUST00002,National Retail,Contract,30,Retail,Active,2021-06-02,4936566
2,CUST00003,XYZ Industries,Contract,30,Consumer Goods,Active,2020-09-04,3102814
3,CUST00004,American Corp,Contract,15,Food/Beverage,Active,2020-11-29,3948027
4,CUST00005,American Distribution,Spot,45,Consumer Goods,Active,2020-02-04,3682564

In [43]:
customer_summary = customers.groupby(
    ["customer_id", "customer_name", "customer_type"],
    as_index=False
).agg(
    annual_revenue=("annual_revenue_potential", "sum")
)

customer_summary.head()

  customer_id          customer_name customer_type  annual_revenue
0   CUST00001        Metro Wholesale     Dedicated          985117
1   CUST00002        National Retail      Contract         4936566
2   CUST00003         XYZ Industries      Contract         3102814
3   CUST00004          American Corp      Contract         3948027
4   CUST00005  American Distribution          Spot         3682564

In [45]:
customer_summary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     200 non-null    object
 1   customer_name   200 non-null    object
 2   customer_type   200 non-null    object
 3   annual_revenue  200 non-null    int64
dtypes: int64(1), object(3)
memory usage: 6.4+ KB

In [47]:
import os

gold_path = r"C:\Users\yashk\OneDrive\Desktop\Logistics_Data_Pipeline\Gold\customer_revenue_summary"

os.makedirs(gold_path, exist_ok=True)

customer_summary.to_csv(
    os.path.join(gold_path, "customer_revenue_summary.csv"),
    index=False
)

print("✅ Customer Revenue Summary saved successfully!")

✅ Customer Revenue Summary saved successfully!

In [55]:
import os
print(os.getcwd())

C:\Users\yashk\OneDrive\Desktop\Logistics_Data_Pipeline\Notebooks

In [59]:
os.listdir("../silver")

['customers',
 'delivery_events',
 'drivers',
 'driver_monthly_metrics',
 'facilities',
 'fuel_purchases',
 'loads',
 'maintenance_records',
 'routes',
 'safety_incidents',
 'trailers',
 'trips',
 'trucks',
 'truck_utilization _metrics']

In [63]:
import os
for item in os.listdir("../Silver"):
    print(item)

customers
delivery_events
drivers
driver_monthly_metrics
facilities
fuel_purchases
loads
maintenance_records
routes
safety_incidents
trailers
trips
trucks
truck_utilization _metrics

In [65]:
import glob
print(glob.glob("../Silver/*"))

['../Silver\\customers', '../Silver\\delivery_events', '../Silver\\drivers', '../Silver\\driver_monthly_metrics', '../Silver\\facilities', '../Silver\\fuel_purchases', '../Silver\\loads', '../Silver\\maintenance_records', '../Silver\\routes', '../Silver\\safety_incidents', '../Silver\\trailers', '../Silver\\trips', '../Silver\\trucks', '../Silver\\truck_utilization _metrics']

In [67]:
print(glob.glob("../Silver/truck*"))

['../Silver\\trucks', '../Silver\\truck_utilization _metrics']

In [73]:
import os

print(os.listdir("../Silver\\truck_utilization _metrics"))

['truck_utilization _metrics.csv']

In [81]:
truck_metrics = pd.read_csv("../Silver\\truck_utilization _metrics/truck_utilization _metrics.csv")

In [84]:
truck_metrics.head()

,truck_id,month,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
0,TRK00001,2022-01-01,22,39269,84792.02,6.78,2,4380.98,63.1,0.710
1,TRK00001,2022-02-01,27,40787,88809.05,6.23,0,0.00,0.0,0.964
2,TRK00001,2022-03-01,34,57422,120453.71,6.49,0,0.00,0.0,1.097
3,TRK00001,2022-04-01,20,34428,73531.28,6.50,2,3548.15,71.8,0.667
4,TRK00001,2022-05-01,16,20851,40791.53,6.38,1,1969.42,43.9,0.516

In [88]:
print(truck_metrics.columns.tolist())

['truck_id', 'month', 'trips_completed', 'total_miles', 'total_revenue', 'average_mpg', 'maintenance_events', 'maintenance_cost', 'downtime_hours', 'utilization_rate']

In [90]:
truck_summary = truck_metrics.groupby("truck_id").agg({
    "trips_completed": "sum",
    "total_miles": "sum",
    "total_revenue": "sum",
    "average_mpg": "mean",
    "maintenance_events": "sum",
    "maintenance_cost": "sum",
    "downtime_hours": "sum",
    "utilization_rate": "mean"
}).reset_index()

truck_summary.head()

,truck_id,trips_completed,total_miles,total_revenue,average_mpg,maintenance_events,maintenance_cost,downtime_hours,utilization_rate
0,TRK00001,951,1356397,2896338.17,6.488611,24,51775.99,713.2,0.867139
1,TRK00002,887,1270572,2712361.86,6.492500,27,54869.04,665.3,0.809583
2,TRK00004,929,1309547,2803602.13,6.498611,22,38561.82,483.2,0.847111
3,TRK00006,878,1278551,2778546.55,6.485556,26,50780.83,587.7,0.801778
4,TRK00007,922,1336736,2887748.17,6.485833,20,25868.97,415.7,0.841528

In [92]:
print(truck_metrics.columns.tolist())

['truck_id', 'month', 'trips_completed', 'total_miles', 'total_revenue', 'average_mpg', 'maintenance_events', 'maintenance_cost', 'downtime_hours', 'utilization_rate']

In [94]:
import os

gold_path = "../Gold/truck_summary"
os.makedirs(gold_path, exist_ok=True)

In [96]:
truck_summary.to_csv(
    "../Gold/truck_summary/truck_summary.csv",
    index=False
)

print("✅ Truck Summary saved successfully!")

✅ Truck Summary saved successfully!

In [98]:
import os

print(os.listdir("../Gold/truck_summary"))

['truck_summary.csv']

In [100]:
routes = pd.read_csv("../Silver/routes/routes.csv")
loads = pd.read_csv("../Silver/loads/loads.csv")

In [102]:
route_summary = loads.merge(routes, on="route_id", how="left")

In [108]:
print(loads.columns.tolist())

['load_id', 'customer_id', 'route_id', 'load_date', 'load_type', 'weight_lbs', 'pieces', 'revenue', 'fuel_surcharge', 'accessorial_charges', 'load_status', 'booking_type']

In [110]:
print(routes.columns.tolist())

['route_id', 'origin_city', 'origin_state', 'destination_city', 'destination_state', 'typical_distance_miles', 'base_rate_per_mile', 'fuel_surcharge_rate', 'typical_transit_days']

In [112]:
route_summary = loads.merge(routes, on="route_id", how="left")

route_summary = route_summary.groupby("route_id").agg({
    "load_id": "count",
    "revenue": "sum",
    "typical_distance_miles": "mean"
}).reset_index()

route_summary.rename(columns={
    "load_id": "total_loads",
    "revenue": "total_revenue",
    "typical_distance_miles": "average_distance"
}, inplace=True)

route_summary.head()

   route_id  total_loads  total_revenue  average_distance
0  RTE00001         1456     1675362.80             677.0
1  RTE00002         1481     2154291.12             697.0
2  RTE00003         1496     7621380.80            2003.0
3  RTE00004         1459     5418160.40            2017.0
4  RTE00005         1479     6236094.68            1749.0

In [114]:
import os

os.makedirs("../Gold/route_summary", exist_ok=True)

route_summary.to_csv(
    "../Gold/route_summary/route_summary.csv",
    index=False
)

print("✅ Route Summary saved successfully!")

✅ Route Summary saved successfully!